version: '3.8'
services:
  db:
    image: postgres:16
    environment:
# se necesita un archivo .env con estos tres parametros que se parezca a esto:
# POSTGRES_USER=<tu_usuario_de_postgres>
# POSTGRES_PASSWORD=<tu_password>
# # POSTGRES_DB=<el_nombre_de_tu_base_de_datos>
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./ui/final
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: